### ISSUE TITLE
cloth-config-9.0.92-fabric incompatible

### ISSUE THREAD

**Issue by kaxlabs** [Bstn1802/AutoReconnect#37] opened 2022-11-20 00:21 UTC
I'm using latest cloth config (9.0.92) and I get this error:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install cloth-config2, version 6.0.0 or later.

**Comment by Bstn1802** [comment] 2022-11-20 21:18
You probably got the forge version of cloth config, literally got the same issue here a week ago or so xD
If that's not the case, please post the full crash report or what ever it is you're getting, so I can look into it further and figure out what could be wrong.

**Comment by cunhar** [comment] 2022-12-29 14:17
I can confirm this is not workign with 9.0.94

**Comment by cunhar** [comment] 2022-12-29 18:55
@Bstn1802 it just crashes with no message error code 1

**Comment by Bstn1802** [comment] 2022-12-30 22:11
I heard that AutoReconnect itself is not working for minecraft 1.19.3. I already removed the tag on curseforge, I didn't get to fix the issue yet tho, but since this issue is probably not related to cloth config at all, since version 9.0.92 and above are mc 1.19.3 versions, I'm closing this issue.
If you believe this actually has to do with cloth config, feel free to reopen this issue with a crash report, which would be really helpful.

**Closed by Bstn1802** 2022-12-30 22:11 UTC
